package GUI;

import Classes.Cliente;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ViewHomeFuncionario extends javax.swing.JFrame {
    Cliente client = null;

    public ViewHomeFuncionario() {
        initComponents();
        lblFuncAgencia.setText("<html><u>Cadastrar Funcionario da Agência</u></html>");
        lblFuncCEE1.setText("<html><u>Cadastrar Funcionario do CEE</u></html>");
        lblFuncCargas.setText("<html><u>Cadastrar Funcionario de Cargas</u></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHead = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        MenuBar = new javax.swing.JPanel();
        lblFuncAgencia = new javax.swing.JLabel();
        lblFuncCargas = new javax.swing.JLabel();
        lblFuncCEE1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHead.setBackground(new java.awt.Color(243, 243, 243));
        pnlHead.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlHead.setMaximumSize(new java.awt.Dimension(163, 49));

        lblLogo.setBackground(new java.awt.Color(153, 153, 153));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/correios/Imagens/logo.png"))); // NOI18N

        MenuBar.setBackground(new java.awt.Color(255, 255, 255));

        lblFuncAgencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFuncAgencia.setForeground(new java.awt.Color(0, 51, 255));
        lblFuncAgencia.setText("Cadastrar Funcionario da Agência");
        lblFuncAgencia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFuncAgenciaMouseMoved(evt);
            }
        });
        lblFuncAgencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuncAgenciaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFuncAgenciaMouseExited(evt);
            }
        });

        lblFuncCargas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFuncCargas.setForeground(new java.awt.Color(0, 51, 255));
        lblFuncCargas.setText("Cadastrar Funcionario de Cargas");
        lblFuncCargas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFuncCargasMouseMoved(evt);
            }
        });
        lblFuncCargas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuncCargasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFuncCargasMouseExited(evt);
            }
        });

        lblFuncCEE1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFuncCEE1.setForeground(new java.awt.Color(0, 51, 255));
        lblFuncCEE1.setText("Cadastrar Funcionario do CEE");
        lblFuncCEE1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFuncCEE1MouseMoved(evt);
            }
        });
        lblFuncCEE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuncCEE1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFuncCEE1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFuncAgencia)
                    .addComponent(lblFuncCargas)
                    .addComponent(lblFuncCEE1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFuncAgencia)
                .addGap(27, 27, 27)
                .addComponent(lblFuncCEE1)
                .addGap(26, 26, 26)
                .addComponent(lblFuncCargas)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFuncAgenciaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncAgenciaMouseMoved
        lblFuncAgencia.setForeground(Color.ORANGE);
    }//GEN-LAST:event_lblFuncAgenciaMouseMoved

    private void lblFuncAgenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncAgenciaMouseExited
        lblFuncAgencia.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblFuncAgenciaMouseExited

    private void lblFuncAgenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncAgenciaMouseClicked
        ViewCadastroFuncAgencia vcadastroFuncAgencia = null;
        try {
            vcadastroFuncAgencia = new ViewCadastroFuncAgencia();
        } catch (ParseException ex) {
            Logger.getLogger(ViewHomeFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewHomeFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        vcadastroFuncAgencia.setVisible(true);
    }//GEN-LAST:event_lblFuncAgenciaMouseClicked

    private void lblFuncCargasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncCargasMouseMoved
         lblFuncCargas.setForeground(Color.ORANGE);
    }//GEN-LAST:event_lblFuncCargasMouseMoved

    private void lblFuncCargasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncCargasMouseClicked
        ViewCadastroFuncCarga vcadastroFuncCarga = null;
        
        try {
            vcadastroFuncCarga = new ViewCadastroFuncCarga();
        } catch (ParseException ex) {
            Logger.getLogger(ViewHomeFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewHomeFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        vcadastroFuncCarga.setVisible(true);
    }//GEN-LAST:event_lblFuncCargasMouseClicked

    private void lblFuncCargasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncCargasMouseExited
         lblFuncCargas.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblFuncCargasMouseExited

    private void lblFuncCEE1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncCEE1MouseMoved
         lblFuncCEE1.setForeground(Color.ORANGE);
    }//GEN-LAST:event_lblFuncCEE1MouseMoved

    private void lblFuncCEE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncCEE1MouseClicked
        ViewCadastroFuncCEE vcadastroFuncCee = null;
      
        try {
            vcadastroFuncCee = new ViewCadastroFuncCEE();
        } catch (ParseException ex) {
            Logger.getLogger(ViewHomeFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewHomeFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        vcadastroFuncCee.setVisible(true);
    }//GEN-LAST:event_lblFuncCEE1MouseClicked

    private void lblFuncCEE1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncCEE1MouseExited
         lblFuncCEE1.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblFuncCEE1MouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel lblFuncAgencia;
    private javax.swing.JLabel lblFuncCEE1;
    private javax.swing.JLabel lblFuncCargas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlHead;
    // End of variables declaration//GEN-END:variables
}
