package correios.GUI;

import correios.Controller.ControllerLogin;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ViewLogin extends javax.swing.JFrame {

    private String cpfCli = null;
    ControllerLogin controllerLogin;
    PreparedStatement psQrCli = null, psQrAdm = null;
    ResultSet resultQrCli = null, resultQrAdm = null;
    String qualTela = null;
    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
        controllerLogin = new ControllerLogin();
        lblCadastrar.setText("<html><u>Cadastrar</u>");

    }
    
    public ViewLogin(Object[] l) {
        initComponents();
        controllerLogin = new ControllerLogin();
        lblCadastrar.setText("<html><u>Cadastrar</u>");
        txtEmail.setText(l[0].toString());
        pwdSenha.setText(l[1].toString());

    }
    public void verificaLogin() throws SQLException {
        String email = txtEmail.getText();
        String senha = new String(pwdSenha.getPassword());  
        System.out.println("Email: "+email+"  Senha: "+senha);
        
        if (email.isEmpty() && senha.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Inisira seu e-mail e sua senha", "Credenciais Inválidas", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
        } else if (email.isEmpty() && !senha.isEmpty()) {
            txtEmail.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Insira seu e-mail", "Credenciais Inválidas", JOptionPane.ERROR_MESSAGE);
        } else if (!email.isEmpty() && senha.isEmpty()) {
            pwdSenha.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Insira sua senha", "Credenciais Inválidas", JOptionPane.ERROR_MESSAGE);
        } else {
            
            Object [] login = {email, senha};
            //se existe cliente, pode abrir a tela de cliente
            ArrayList<Object[]> loginResultado = controllerLogin.buscarLogin_DAO(login, "Cliente");
            System.out.println("Login Resultado: "+loginResultado);
            if(loginResultado.size()>0){
                for (Object conta : loginResultado ) {  
                    Object resultado[] = (Object[]) conta;  // 0 = codLogin, 1 = fk_Cliente_cpf
                    cpfCli = (String) resultado[1];
                    qualTela = "viewHomeCliente";
                    System.out.println("Cod Login: " + resultado[0] + " Cpf Cliente: " + cpfCli);
                }
            }else { //senão, verifica se existe adm  
                //se existe adm, abre a tela de admn
                loginResultado = controllerLogin.buscarLogin_DAO(login, "Administrador");
                System.out.println("Login Resultado: "+loginResultado);
                if(loginResultado!=null){
                    for (Object conta : loginResultado ) {                
                        Object resultado[] = (Object[]) conta;  // 0 = codLogin, 1 = nomeCargo
                        String nomeCargo = (String) resultado[1];
                        if(nomeCargo.equals("Administrador")){
                            qualTela = "viewHomeFuncionario";
                            System.out.println("Cod Login: " + resultado[0] + " Nome Cargo: " + resultado[1]);
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Você não é um Administrador", "Credenciais Inválidas", JOptionPane.ERROR_MESSAGE);
                        }  
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Login não existe", "Credenciais Inválidas", JOptionPane.ERROR_MESSAGE);
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        pnlBody = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pwdSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblCadastrar = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pnlHead = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 153));
        lblTitle.setText("Entre com seu usuário e senha");
        lblTitle.setAlignmentX(0.5F);

        pwdSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 0, 14))); // NOI18N

        btnEntrar.setBackground(new java.awt.Color(0, 51, 255));
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(0, 51, 255));
        lblCadastrar.setText("Cadastrar");
        lblCadastrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseMoved(evt);
            }
        });
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseExited(evt);
            }
        });

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 0, 14))); // NOI18N

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pwdSenha)
                            .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail)))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblCadastrar)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblCadastrar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBody, java.awt.BorderLayout.CENTER);

        pnlHead.setBackground(new java.awt.Color(243, 243, 243));
        pnlHead.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlHead.setMaximumSize(new java.awt.Dimension(163, 49));

        lblLogo.setBackground(new java.awt.Color(153, 153, 153));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/correios/Imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlHead, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseMoved
        lblCadastrar.setForeground(Color.ORANGE);

    }//GEN-LAST:event_lblCadastrarMouseMoved

    private void lblCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseExited
        lblCadastrar.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblCadastrarMouseExited

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try {
            verificaLogin();
        } catch (SQLException ex) {
            Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (qualTela != null) {
            if (qualTela.equals("viewHomeCliente")) {
                controllerLogin.abrirViewHomeCliente(cpfCli);
                this.dispose();
            } else if (qualTela.equals("viewHomeFuncionario")) {
                controllerLogin.abrirViewHomeFuncionario();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "E-mail ou Senha Incorretos", "Credenciais Inválidas", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        try {
            controllerLogin.abrirViewCadastroLogin();
        } catch (ParseException ex) {
            Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
            
    }//GEN-LAST:event_lblCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    //try {
    /*   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });*/
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
